image:
- Visual Studio 2019
- Visual Studio 2017
- Ubuntu
- macos

configuration:
- Minio
- AWS
- AWS-HTTP
- WebscaleDemo
- GCS

build: off

# Version number
version: 0.0.1.{build}

# Ignore testing a commit if only the README.md file changed or if the commit message contains [notest]
skip_commits:
  message: /\[notest\]/
  files:
    - README.md
    - S3-Client-Tutorial.md
    - LICENSE

# Do not test on tags
skip_tags: true

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6GMJ5njfnun87K3Ph4yKz/A00od/m0n+OlQ+M6B9JBn73aANr4CObDwnwyIw96ZKp8GGFGdDCQOoKVk+2kjGv/sBZZaLw3kXWgR8RmCIYCD6gtS5O/Zj1b403z8X3rFARsUliNJqYHH8TZGLwNrQy8/GklaqWqyXe2RYr2w7QCU+5zOMFyhibqRcRlBYurhk2LWs95uxdzVAD+xkZXfFTSXUUTCBrlbv+jkRHgAgM9x6Ki+P8VnZ6FnMAs5wI8aP38zHjZoA9ZyxgsZht+1YWazlAjiH2b114oezwgbQQDtSYm5xATmhfZtghrDzsfqCxBDSUKgGlgjmplxCGFl9j florianf@florianf-mac-0

# Install Pester for testing, setup AWS Profiles and deploy minio via docker
install:
  - ps: $PSVersionTable
  - cmd: mkdir %USERPROFILE%\.aws
  - cmd: mkdir %USERPROFILE%\.sgw
  - cmd: move etc\.aws\config %USERPROFILE%\.aws\config
  - cmd: move etc\.aws\credentials %USERPROFILE%\.aws\credentials
  - sh: mkdir $HOME/.aws
  - sh: mkdir $HOME/.sgw
  - sh: mv etc/.aws/config $HOME/.aws/config
  - sh: mv etc/.aws/credentials $HOME/.aws/credentials

#before_test:
# enable SSH
#  - sh: export APPVEYOR_SSH_BLOCK=true
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
# enable RDP
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Invoke Pester to run all of the unit tests, then save the results into XML in order to populate the AppVeyor tests section
# If any of the tests fail, consider the pipeline failed
test_script:
#  - ps: $DebugPreference = "Continue"
#  - ps: $VerbosePreference = "Continue"
  - ps: Get-Culture
  - ps: $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru -Script @{Path="./src/S3-Client.Tests.ps1";Parameters=@{ProfileName=$($env:CONFIGURATION)}} -TestName "List Buckets"
  - ps: (New-Object System.Net.WebClient).UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
